language: cpp
compiler:
  - clang
notifications:
  email: false
env:
    matrix: 
        - JULIAVERSION="juliareleases" 
        - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'versioninfo(); Pkg.init(); Pkg.add("BinDeps"); Pkg.add("Graphs"); Pkg.clone(pwd()); Pkg.build("Metis")'
  - julia -e 'using Metis; @assert isdefined(:Metis); @assert typeof(Metis) === Module'
  - julia --code-coverage ./test/runtests.jl
after_success:
  - julia -e 'cd(Pkg.dir("Metis")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
